# Generated by Django 4.0.3 on 2022-03-30 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_records_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='user_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
    ]
