# Generated by Django 4.0.3 on 2022-04-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_records_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='user_image',
        ),
    ]
